# Default values for the IPCCAR5 - glaciers module
# These values are used when creating new experiments and can be overridden in experiment metadata

# internal note: Image information and Location file defaults DO NOT belong here.

options:
  refyear_start: 1986
  refyear_end: 2005
  start_year: 2005
  end_year: 2301
  tlm_flag: 1
  nsamps: 100
  #ntsamps: 450
  #nmsamps: 1000
  use_gmip: 2
  chunksize: 20

inputs:
  glacier_fraction_file: glacier_fraction.txt
