# Default values for the FittedISMIP GRIS module
# These values are used when creating new experiments and can be overridden in experiment metadata

# internal note: Image information andLocation file defaults DO NOT belong here.

options:
  tlm_flag: 1
  pyear_start: 2020
  pyear_end: 2100
  #cyear_start: None
  cyear_end: 2100
  pyear_step: 10
  baseyear: 2005
  chunksize: 50

inputs:
  gris_parm_file: "FittedParms_GrIS_ALL.csv"
  wais_parm_file: "FittedParms_AIS_WAIS.csv"
  eais_parm_file: "FittedParms_AIS_EAIS.csv"
  pen_parm_file: "FittedParms_AIS_PEN.csv"
