version: '3.8'
services:
   fair:
      image: ghcr.io/fact-sealevel/fair-temperature:0.2.1
      volumes:
         - /Users/emmamarshall/Desktop/facts_work/facts_v2/fair/data/input:/mnt/fair_in
         - ./v2_experiments/my_facts_experiment/data/output:/mnt/fair_out
      restart: 'no'
      command:
         - --pipeline-id=AAAA
         - --nsamps=500
         - --scenario=ssp585
         - --seed=1234
         - --cyear-start=1850
         - --cyear-end=1900
         - --smooth-win=19
         - --rcmip-file=/mnt/fair_in/rcmip
         - --param-file=/mnt/fair_in/parameters
         - --output-ohc-file=/mnt/fair_out/ohc.nc
         - --output-gsat-file=/mnt/fair_out/gsat.nc
         - --output-climate-file=/mnt/fair_out/climate.nc
   bamber19-icesheets:
      image: ghcr.io/fact-sealevel/bamber19-icesheets:0.1.0
      depends_on:
         fair:
            condition: service_completed_successfully
      volumes:
         - /Users/emmamarshall/Desktop/facts_work/facts_v2/bamber19-icesheets/data/input:/mnt/bamber19_icesheets_in
         - ./v2_experiments/my_facts_experiment/data/output:/mnt/bamber19_icesheets_out
         - ./v2_experiments/my_facts_experiment/data/output:/mnt/fair_out
      restart: 'no'
      command:
         - --pipeline-id=AAAA
         - --nsamps=500
         - --baseyear=2005
         - --pyear-start=2020
         - --pyear-end=2150
         - --pyear-step=10
         - --scenario=ssp585
         - --seed=1234
         - --replace=True
         - --climate-data-file=/mnt/fair_out/climate.nc
         - --slr-proj-mat-file=/mnt/bamber19_icesheets_in/SLRProjections190726core_SEJ_full.mat
         - --ais-gslr-outfile=/mnt/bamber19_icesheets_out/ais_gslr.nc
         - --eais-gslr-outfile=/mnt/bamber19_icesheets_out/eais_gslr.nc
         - --wais-gslr-outfile=/mnt/bamber19_icesheets_out/wais_gslr.nc
         - --gis-gslr-outfile=/mnt/bamber19_icesheets_out/gis_gslr.nc
